name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/LaraCryptSharp.sln', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
          path: ~/.nuget/packages
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build -c Release